import { configureStore } from "@reduxjs/toolkit";
import { setupListeners } from "@reduxjs/toolkit/query/react";
import { apiSlice } from "./api/apiSlice.js";
import authReducer from "./Features/auth/AuthSlice.js";
import favoritesReducer from "./Features/favorites/FavoriteSlice.js";
import CartSliceReducer from "../redux/Features/cart/CartSlice.js";
import shopReducer from "../redux/Features/shop/ShopSlice.js";
import { getFavoritesFromLocalStorage } from "../Utils/localStorage.js";

const initialFavorites = getFavoritesFromLocalStorage() || [];
//Fetches the initial favorites from the browser's local storage
const store = configureStore({
  reducer: {
    [apiSlice.reducerPath]: apiSlice.reducer, //adds a reducer generated by the apiSlice
    auth: authReducer,
    favorites: favoritesReducer,
    cart: CartSliceReducer,
    shop: shopReducer,
  },

  preloadedState: {
   favorites: initialFavorites,
  },

  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(apiSlice.middleware),
  devTools: true,
});

setupListeners(store.dispatch);
export default store;